drop table if exists geek_favorite_film
drop table if exists geek_favorite_game
drop table if exists geek_favorite_super_hero
drop table if exists super_hero
drop table if exists game
drop table if exists film
drop table if exists geek

create table if not exists film (id bigint generated by default as identity, name varchar(255) not null, primary key (id))
create table if not exists game (id bigint generated by default as identity, game_style varchar(255) not null, name varchar(255) not null, price decimal(19,2), primary key (id))
create table if not exists geek (id bigint generated by default as identity, birth_date date, email varchar(255), favorite_language varchar(255) not null, geek_name varchar(255) not null, has_glasses boolean, real_name varchar(255) not null, primary key (id))
create table if not exists geek_favorite_film (geek_id bigint not null, favorite_film_id bigint not null)
create table if not exists geek_favorite_game (geek_id bigint not null, favorite_game_id bigint not null)
create table if not exists geek_favorite_super_hero (geek_id bigint not null, favorite_super_hero_id bigint not null)
create table if not exists super_hero (id bigint generated by default as identity, name varchar(255) not null, primary key (id))
alter table geek add constraint UK_rcpa43rqrcurac67v2kdr6910 unique (geek_name)
alter table geek_favorite_film add constraint UK_l33365hlr74u1jgqgvb3xhl3j unique (favorite_film_id)
alter table geek_favorite_game add constraint UK_fb7h4qmacc0abmojd29ijmkwt unique (favorite_game_id)
alter table geek_favorite_super_hero add constraint UK_4tpxas2qqvq0f4oeer6tplahx unique (favorite_super_hero_id)
alter table geek_favorite_film add constraint FKdm7if7xnkbj1wgq17vhcc5xrg foreign key (favorite_film_id) references film
alter table geek_favorite_film add constraint FKpwu0j6fqr08qdi2s7h6fyae0y foreign key (geek_id) references geek
alter table geek_favorite_game add constraint FKe5gapts4nt04aqgkkj2dx17ht foreign key (favorite_game_id) references game
alter table geek_favorite_game add constraint FKg97slmj6klx8yt4m750rf0xic foreign key (geek_id) references geek
alter table geek_favorite_super_hero add constraint FKoce3i3uqhtxqmyp7xx1kp16qd foreign key (favorite_super_hero_id) references super_hero
alter table geek_favorite_super_hero add constraint FK1pmlfcr01rxo9px3vxd2ektmq foreign key (geek_id) references geek
